# Generated by Django 2.1.15 on 2021-01-23 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('post_type', models.CharField(choices=[('post', 'Post'), ('project', 'Project'), ('subtask', 'Subtask')], default='Project', max_length=7)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Created_by', to=settings.AUTH_USER_MODEL)),
                ('post_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskupdate.Post_Details')),
            ],
            options={
                'verbose_name': 'Post_Detail',
                'verbose_name_plural': 'Post_Details',
            },
        ),
    ]
