# Generated by Django 2.1.15 on 2021-01-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskupdate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_details',
            old_name='name',
            new_name='post_name',
        ),
        migrations.AlterField(
            model_name='post_details',
            name='post_type',
            field=models.CharField(choices=[('task', 'Task'), ('project', 'Project'), ('subtask', 'Subtask')], default='Project', max_length=7),
        ),
    ]
